version: "3.8"

services:
  redis:
    image: redis

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A proj worker --loglevel=INFO
    depends_on:
      - web
      - redis
